flax version needs to be updated in requirements, I got this error while trying: "TypeError: __init__() got an unexpected keyword argument 'step_offset'" , and that was because of the flax version mismatch
PiperOrigin-RevId: 356817800