Fix auto reset attribute name
_handle_auto_reset does not exist, this is a revert to the old attribute name.

`AttributeError: 'AdversarialEnv' object has no attribute '_handle_auto_reset'`